// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tipo_publicação : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipo_publicação));
        
        string IMigrationMetadata.Id
        {
            get { return "201312032259373_tipo_publicação"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
