// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cat_livro_cat_revista : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cat_livro_cat_revista));
        
        string IMigrationMetadata.Id
        {
            get { return "201312032258217_cat_livro_cat_revista"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
