// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updRelacaoClienteCarrinho : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updRelacaoClienteCarrinho));
        
        string IMigrationMetadata.Id
        {
            get { return "201312061935506_updRelacaoClienteCarrinho"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
