// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class linhas_fat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linhas_fat));
        
        string IMigrationMetadata.Id
        {
            get { return "201312032302282_linhas_fat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
