// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updFaturaRetirarNumero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updFaturaRetirarNumero));
        
        string IMigrationMetadata.Id
        {
            get { return "201312071704294_updFaturaRetirarNumero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
