// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updGestProd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updGestProd));
        
        string IMigrationMetadata.Id
        {
            get { return "201312061916038_updGestProd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
