// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addURIagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addURIagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201312032254361_addURIagain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
