// <auto-generated />
namespace IDEIBiblio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeURI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeURI));
        
        string IMigrationMetadata.Id
        {
            get { return "201312032253135_removeURI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
